// frontend-vite/src/components/FooterComponent.vue
<template>
  <footer class="footer mt-5 w-100">
    <div class="row py-3 container-fluid">
      <div class="col-4 text-start ps-5">
        <a target="_blank" rel="noopener" href="/manual.pdf">
          <span>Manual de Usuario</span>
        </a>
      </div>
      <div class="col-4 text-center">
        <a target="_blank" rel="noopener"
          href="http://intra.mdef.es/portal/intradef/Ministerio_de_Defensa/Ejercito_de_Tierra">
          <span class="me-4">Ejército de Tierra</span>
        </a>
        <a target="_blank" rel="noopener"
          href="http://intra.mdef.es/portal/intradef/Ministerio_de_Defensa/Ejercito_de_Tierra_-_UCO/UCO/UCO:132">
          <span>CENAD San Gregorio</span>
        </a>
      </div>
      <div class="col-4 text-end pe-5">
        <RouterLink :to="{ name: 'cenads' }">
          <span>Superadministrador</span>
        </RouterLink>
      </div>
    </div>
  </footer>
</template>
<script setup lang="ts">
import { RouterLink } from 'vue-router';
</script>
<style lang="scss">
footer {
  background: #A3B18A;
}

footer a {
  color: #344E41;
}

footer a:hover {
  color: white;
}
</style>

// frontend/src/app/core/shell/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {
  constructor() { }

  ngOnInit() { }

}

<footer class="footer">
  <div class="row py-3">
    <div class="col-8 text-right">
      <a target="_blank" rel="noopener"
        href="http://intra.mdef.es/portal/intradef/Ministerio_de_Defensa/Ejercito_de_Tierra">
        <span class="mr-4">Ejército de Tierra</span>
      </a>
      <a target="_blank" rel="noopener"
        href="http://intra.mdef.es/portal/intradef/Ministerio_de_Defensa/Ejercito_de_Tierra_-_UCO/UCO/UCO:132">
        <span>CENAD San Gregorio</span>
      </a>
    </div>
    <div class="col-4 text-right pr-5">
      <a routerLink="superadministrador">
        <span>Superadministrador</span>
      </a>
    </div>
    <!--luego lo quitaremos de aqui porque ira dentro de la pagina de un cenad concreto-->
    <div class="col text-right pr-5">
      <a routerLink="categorias">
        <span>Categorias</span>
      </a>
    </div>
  </div>
</footer>
